### ISSUE TITLE
您好请教一下数据预处理部分

### ISSUE THREAD

**Issue by zhangluustb** [ZhengJun-AI/MoirePhotoRestoration-MCNN#2]
您好，我下载了testdata，发现每个图片都有一个黑色“相框”用作对齐，但是在您的代码中没有“对齐”的代码，请问您是怎么理解和处理的呢？多谢指教

**Comment by ZhengJun-AI** [comment]
> 您好，我下载了testdata，发现每个图片都有一个黑色“相框”用作对齐，但是在您的代码中没有“对齐”的代码，请问您是怎么理解和处理的呢？多谢指教

抱歉，当初在实现的时候偷懒没有做这一步，而是采用了CenterCrop去规避…参考过大多数论文后，我个人认为正确的做法应当是对齐之后采用Resize，然而当初在尝试复现的时候我还比较懵懂。
事实上“对齐”这一步是很重要的，应该是会对实验结果产生很大的影响 (训练得出的PSNR与最优值可能相去甚远)，后续有空的话我会把那部分代码补上，或者说把这整个复现代码优化一下。

**Comment by zhangluustb** [comment]
> > 您好，我下载了testdata，发现每个图片都有一个黑色“相框”用作对齐，但是在您的代码中没有“对齐”的代码，请问您是怎么理解和处理的呢？多谢指教
> 
> 抱歉，当初在实现的时候偷懒没有做这一步，而是采用了CenterCrop去规避…参考过大多数论文后，我个人认为正确的做法应当是对齐之后采用Resize，然而当初在尝试复现的时候我还比较懵懂。
> 事实上“对齐”这一步是很重要的，应该是会对实验结果产生很大的影响 (训练得出的PSNR与最优值可能相去甚远)，后续有空的话我会把那部分代码补上，或者说把这整个复现代码优化一下。

多谢及时回复，我突然意识到好像数据集就是warp对齐之后的，所以大都没有对齐这一步，也通过一张source-target进行了验证，大概率是正确的。
![test](https://user-images.githubusercontent.com/16039586/111452284-54362c00-874d-11eb-98af-e87a6700c7fb.jpg)

**Comment by ZhengJun-AI** [comment]
> > > 您好，我下载了testdata，发现每个图片都有一个黑色“相框”用作对齐，但是在您的代码中没有“对齐”的代码，请问您是怎么理解和处理的呢？多谢指教
> > 
> > 
> > 抱歉，当初在实现的时候偷懒没有做这一步，而是采用了CenterCrop去规避…参考过大多数论文后，我个人认为正确的做法应当是对齐之后采用Resize，然而当初在尝试复现的时候我还比较懵懂。
> > 事实上“对齐”这一步是很重要的，应该是会对实验结果产生很大的影响 (训练得出的PSNR与最优值可能相去甚远)，后续有空的话我会把那部分代码补上，或者说把这整个复现代码优化一下。
> 
> 多谢及时回复，我突然意识到好像数据集就是warp对齐之后的，所以大都没有对齐这一步，也通过一张source-target进行了验证，大概率是正确的。
> ![test](https://user-images.githubusercontent.com/16039586/111452284-54362c00-874d-11eb-98af-e87a6700c7fb.jpg)

事实上，有个别论文指出了这个数据集的图片对齐的问题…所以现在新的论文里面，进行SOTA对比会引入其他的数据集，但是也依旧会保留这个作为benchmark。
简而言之，用这个数据集进行训练很难得到好的结果，目前看来最强的MBCNN的PSNR也只能达到28+。至于我个人的复现，至今为止最好的结果也只是24+，距离论文所提及的26+遥遥无期，并且我个人对此持有怀疑态度。因为MopNet在我看来是很有效的方法，然而和这篇DMCNN相比，结果上也只是相对持平。

**Comment by zhangluustb** [comment]
多谢您的宝贵经验*-*
