### ISSUE TITLE
一个比较严重的模型代码错误

### ISSUE THREAD

**Issue by XinYu-Andy** [ZhengJun-AI/MoirePhotoRestoration-MCNN#4]
你好，我注意到在def conv_block这个函数里，不能用初始化一个卷积核到列表里再乘5，因为这样你5个卷积核是共享参数的，事实上是只有一个卷积但网络循环经过了五次。
这也是为什么我测参数量时发现不对，多次debug发现了这个漏洞。
或许更改一下这里就可以复现出report的结果。

祝好。

**Comment by jwwang7** [comment]
您好，想请问您一下这里该如何修改，能否看看您是怎么修改的，非常感谢！

**Comment by ZhengJun-AI** [comment]
你好，邮件已收到！——学委 郑均

**Comment by XinYu-Andy** [comment]
> 您好，想请问您一下这里该如何修改，能否看看您是怎么修改的，非常感谢！

应该像这份代码里9-16行那样写就好了。

**Comment by jwwang7** [comment]
> > 您好，想请问您一下这里该如何修改，能否看看您是怎么修改的，非常感谢！
> 
> 应该像这份代码里9-16行那样写就好了。

改了以后代码目前能运行了，我还是初学者，非常感谢您的指导！

**Comment by ZhengJun-AI** [comment]
你好，邮件已收到！——学委 郑均
