### ISSUE TITLE
The data download link

### ISSUE THREAD

**Issue by jiamingNo1** [ZhengJun-AI/MoirePhotoRestoration-MCNN#5]
The baidu network disk link does not work, Can you provide a new baidu nework dist link?

**Comment by ZhengJun-AI** [comment]
你好，邮件已收到！——学委 郑均

**Comment by ZhengJun-AI** [comment]
I check the link carefully, and it seems that things have been okay. Maybe you should try again or use another link to download the file.

**Comment by jiamingNo1** [comment]
> I check the link carefully, and it seems that things have been okay. Maybe you should try again or use another link to download the file.

thx, I have downloaded the data
