### ISSUE TITLE
摩尔纹生成

### ISSUE THREAD

**Issue by qilong-zhang** [ZhengJun-AI/MoirePhotoRestoration-MCNN#6]
您好，请问一下您有摩尔纹模拟的python代码？我最近也在做相关研究，想尝试模拟一下摩尔纹，但似乎没找到开源的代码。

**Comment by ZhengJun-AI** [comment]
> 您好，请问一下您有摩尔纹模拟的python代码？我最近也在做相关研究，想尝试模拟一下摩尔纹，但似乎没找到开源的代码。

没有。印象中，模拟出效果好的摩尔纹并不trivial…不过我已经很久没有接触low-level vision了。
