### ISSUE TITLE
No access to Google Drive download link

### ISSUE THREAD

**Issue by pavelshutov-pr3vision** [ZhengJun-AI/MoirePhotoRestoration-MCNN#7]
Hello!

I started downloading the dataset, but access to the dataset has been closed since last week when following the link to google drive. I also requested access via this link, but a week later I still have not received a response.

**Comment by ZhengJun-AI** [comment]
> Hello!
> 
> I started downloading the dataset, but access to the dataset has been closed since last week when following the link to google drive. I also requested access via this link, but a week later I still have not received a response.

Bad news. I also need to request access, because original files are not stored in my google drive. It's recommended to download the dataset by another link.

**Comment by pavelshutov-pr3vision** [comment]
Oh I get it. Thanks for the answer! Downloading via Baidu unfortunately is not so easy for me 😞

**Comment by Fapannen** [comment]
Hi @ZhengJun-AI , is there any update for the permissions to the google Drive, or do we still need to download via Baidu? Navigating through Chinese website is not so easy.

**Comment by ZhengJun-AI** [comment]
> Hi @ZhengJun-AI , is there any update for the permissions to the google Drive, or do we still need to download via Baidu? Navigating through Chinese website is not so easy.

sry, i think maybe you should contact the author of the dataset with the google Drive link...

**Comment by KunalPandharkar** [comment]
Hi @ZhengJun-AI, Your work is good, Im from india and i cant access the pan.baidu will you please share any other link for the dataset ?

**Comment by ZhengJun-AI** [comment]
> Hi @ZhengJun-AI, Your work is good, Im from india and i cant access the pan.baidu will you please share any other link for the dataset ?

i can upload the dataset to HuggingFace, but i need at least one week to do this... WIP

**Comment by KunalPandharkar** [comment]
> > Hi @ZhengJun-AI, Your work is good, Im from india and i cant access the pan.baidu will you please share any other link for the dataset ?
> 
> i can upload the dataset to HuggingFace, but i need at least one week to do this... WIP

Thank you for updating me on the progress regarding the dataset upload to HuggingFace. Your efforts are truly appreciated. Please notify us once uploded.

**Comment by ZhengJun-AI** [comment]
> > > Hi @ZhengJun-AI, Your work is good, Im from india and i cant access the pan.baidu will you please share any other link for the dataset ?
> > 
> > 
> > i can upload the dataset to HuggingFace, but i need at least one week to do this... WIP
> 
> Thank you for updating me on the progress regarding the dataset upload to HuggingFace. Your efforts are truly appreciated. Please notify us once uploded.

Already uploaded part of it.
link: https://huggingface.co/datasets/zxbsmk/TIP-2018
