### ISSUE TITLE
Questions about the dataset

### ISSUE THREAD

**Issue by shallowdream204** [ZhengJun-AI/MoirePhotoRestoration-MCNN#8]
Thanks a lot for sharing the dataset and code. 
I've noticed that in most paper[1,2,3] introductions, it is mentioned that the TIP2018 dataset contains **135,000 images with a resolution of approximately 400x400**. However, the dataset downloaded from the Baidu Cloud link has **a smaller number of images than 135,000 and a resolution of 800x800**. Is this normal?
1. Real-Time Image Demoireing on Mobile Devices. ICLR2023.
2. Towards Efficient and Scale-Robust Ultra-High-Definition Image Demoireing. ECCV2022.
3. FHDe2Net: Full High Definition Demoireing Network. ECCV2020.

**Comment by ZhengJun-AI** [comment]
Yes, the TIP2018 dataset doesn't match the description in the paper. You can also see the table shown in https://github.com/ZhengJun-AI/MoirePhotoRestoration-MCNN#dataset

I suppose papers you mentioned directly copy the description from the original paper.

**Comment by shallowdream0204** [comment]
Thank you for your prompt response. Do we need to crop the central area of the image during testing, or just test with the entire image?

**Comment by shallowdream204** [comment]
Thank you for your prompt response. Do we need to crop the central area of the image during testing, or just test with the entire image?

> Yes, the TIP2018 dataset doesn't match the description in the paper. You can also see the table shown in https://github.com/ZhengJun-AI/MoirePhotoRestoration-MCNN#dataset
> 
> I suppose papers you mentioned directly copy the description from the original paper.

**Comment by ZhengJun-AI** [comment]
> Thank you for your prompt response. Do we need to crop the central area of the image during testing, or just test with the entire image?
> 
> > Yes, the TIP2018 dataset doesn't match the description in the paper. You can also see the table shown in [ZhengJun-AI/MoirePhotoRestoration-MCNN#dataset](https://github.com/ZhengJun-AI/MoirePhotoRestoration-MCNN#dataset)
> > I suppose papers you mentioned directly copy the description from the original paper.

The authors use **centercrop** if my memory serves me right... Maybe you should read the original paper carefully, because I do not keey track of demoiring fo a long time.

**Comment by shallowdream204** [comment]
Thank you very much for your timely response before the CVPR 2024 deadline. I found the code for cropping at [the ECCV 2022 paper](https://github.com/CVMI-Lab/UHDM/blob/main/dataset/load_data.py#L248). Thanks again.

> > Thank you for your prompt response. Do we need to crop the central area of the image during testing, or just test with the entire image?
> > > Yes, the TIP2018 dataset doesn't match the description in the paper. You can also see the table shown in [ZhengJun-AI/MoirePhotoRestoration-MCNN#dataset](https://github.com/ZhengJun-AI/MoirePhotoRestoration-MCNN#dataset)
> > > I suppose papers you mentioned directly copy the description from the original paper.
> 
> The authors use **centercrop** if my memory serves me right... Maybe you should read the original paper carefully, because I do not keey track of demoiring fo a long time.
